#!/usr/bin/env bash
_PLUGIN_ROOT="${CLAUDE_PLUGIN_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/..}"
# build-composed-agents.sh
#
# Generalized base + delta agent file composer.
# Composes <namespace>-base.md + per-variant <namespace>-delta-*.md files into
# generated agent definitions in ${CLAUDE_PLUGIN_ROOT}/agents/.
#
# Each namespace provides a sourceable meta file at <deltas-dir>/<namespace>-meta.sh
# which defines variant -> (model, color, description) mappings and optional base
# content substitutions. See reviewer-meta.sh and investigator-meta.sh for examples.
#
# Usage:
#   bash build-composed-agents.sh --namespace <ns> \
#        [--base PATH] [--deltas DIR] [--output DIR] [--expect-count N] \
#        [--generator-name NAME]
#
# Options:
#   --namespace NS      Required. Namespace prefix (e.g., "reviewer", "investigator").
#   --base PATH         Path to <ns>-base.md (default: <deltas>/<ns>-base.md).
#   --deltas DIR        Directory containing <ns>-delta-*.md files
#                       (default: ${CLAUDE_PLUGIN_ROOT}/docs/workflows/prompts).
#   --output DIR        Output directory for generated agents
#                       (default: ${CLAUDE_PLUGIN_ROOT}/agents/).
#   --expect-count N    Expected delta count; exit non-zero on mismatch.
#   --generator-name N  Name written into the "generated by" comment of each agent
#                       file (default: this script's basename). Wrappers pass their
#                       own name to preserve byte-identical output across renames.
#
# HASH_ALGORITHM: sha256 of (substituted_base_content + "\n" + delta_content).
# The hash is over content only — the frontmatter and the "generated by" comment
# are NOT in the hash, so changing the generator name does not invalidate hashes.
#
# Atomic write: all files are generated in a temp dir; only on full success are
# they copied to the output dir.

set -euo pipefail

# ── Portable sha256 wrapper ──────────────────────────────────────────────────
_sha256() {
    if command -v sha256sum &>/dev/null; then
        sha256sum | awk '{print $1}'
    elif command -v shasum &>/dev/null; then
        shasum -a 256 | awk '{print $1}'
    else
        echo "ERROR: no sha256sum or shasum available" >&2
        return 1
    fi
}

# ── Defaults ─────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_BASENAME="$(basename "${BASH_SOURCE[0]}")"
REPO_ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)"
_PLUGIN_GIT_PATH="${_PLUGIN_ROOT#"$(git -C "$_PLUGIN_ROOT" rev-parse --show-toplevel)/"}"
DSO_PLUGIN_DIR="${REPO_ROOT}/${_PLUGIN_GIT_PATH}"

NAMESPACE=""
BASE_FILE=""
DELTAS_DIR=""
OUTPUT_DIR=""
EXPECT_COUNT=""
GENERATOR_NAME=""
META_FILE=""

# ── Parse arguments ──────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --namespace)      NAMESPACE="$2"; shift 2 ;;
        --base)           BASE_FILE="$2"; shift 2 ;;
        --deltas)         DELTAS_DIR="$2"; shift 2 ;;
        --output)         OUTPUT_DIR="$2"; shift 2 ;;
        --meta)           META_FILE="$2"; shift 2 ;;
        --expect-count)   EXPECT_COUNT="$2"; shift 2 ;;
        --generator-name) GENERATOR_NAME="$2"; shift 2 ;;
        *) echo "ERROR: unknown argument: $1" >&2; exit 1 ;;
    esac
done

if [[ -z "$NAMESPACE" ]]; then
    echo "ERROR: --namespace is required" >&2
    exit 1
fi

# Apply defaults
_DEFAULT_PROMPTS_DIR="$DSO_PLUGIN_DIR/docs/workflows/prompts"
: "${DELTAS_DIR:=$_DEFAULT_PROMPTS_DIR}"
: "${BASE_FILE:=$DELTAS_DIR/${NAMESPACE}-base.md}"
: "${OUTPUT_DIR:=$DSO_PLUGIN_DIR/agents}"
: "${GENERATOR_NAME:=$SCRIPT_BASENAME}"

# Meta file resolution: explicit --meta wins; else look in deltas dir; else fall
# back to the default prompts dir (allows tests to pass --deltas pointing at a
# fixture without needing to copy the namespace meta file).
if [[ -z "$META_FILE" ]]; then
    if [[ -f "$DELTAS_DIR/${NAMESPACE}-meta.sh" ]]; then
        META_FILE="$DELTAS_DIR/${NAMESPACE}-meta.sh"
    else
        META_FILE="$_DEFAULT_PROMPTS_DIR/${NAMESPACE}-meta.sh"
    fi
fi

# ── Validate inputs ─────────────────────────────────────────────────────────
if [[ ! -f "$BASE_FILE" ]]; then
    echo "ERROR: base file not found: $BASE_FILE" >&2
    exit 1
fi
if [[ ! -f "$META_FILE" ]]; then
    echo "ERROR: meta file not found: $META_FILE" >&2
    exit 1
fi

# Source meta file. It must define:
#   _meta_model_for <variant>        -> echo model
#   _meta_color_for <variant>        -> echo color
#   _meta_description_for <variant>  -> echo description
#   _meta_substitute_base <variant>  -> read base on stdin, write substituted base on stdout
#                                       (default: cat — no substitution)
#   _meta_output_prefix              -> string prepended to <variant> for filename
#                                       (default: "${NAMESPACE}-")
# shellcheck source=/dev/null
source "$META_FILE"

# Default substitute hook if meta didn't define one
if ! declare -F _meta_substitute_base >/dev/null; then
    _meta_substitute_base() { cat; }
fi
: "${_meta_output_prefix:=${NAMESPACE}-}"

# Discover delta files
mapfile -t DELTA_FILES < <(find "$DELTAS_DIR" -maxdepth 1 -name "${NAMESPACE}-delta-*.md" -type f | sort)

if [[ ${#DELTA_FILES[@]} -eq 0 ]]; then
    echo "ERROR: no ${NAMESPACE}-delta-*.md files found in: $DELTAS_DIR" >&2
    exit 1
fi

if [[ -n "$EXPECT_COUNT" && "${#DELTA_FILES[@]}" -ne "$EXPECT_COUNT" ]]; then
    echo "ERROR: expected $EXPECT_COUNT delta files, found ${#DELTA_FILES[@]}" >&2
    exit 1
fi

# ── Read base content once ───────────────────────────────────────────────────
BASE_CONTENT="$(cat "$BASE_FILE")"

# ── Atomic write: generate all files in temp dir ─────────────────────────────
TEMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TEMP_DIR"' EXIT

for delta_file in "${DELTA_FILES[@]}"; do
    basename_f="$(basename "$delta_file")"
    variant="${basename_f#"${NAMESPACE}"-delta-}"
    variant="${variant%.md}"

    model="$(_meta_model_for "$variant")" || exit 1
    color="$(_meta_color_for "$variant")" || exit 1
    description="$(_meta_description_for "$variant")" || exit 1

    delta_content="$(cat "$delta_file")"

    # Apply per-variant base substitutions (e.g., reviewer's {{CANONICAL_TIER}}).
    base_content_substituted="$(printf '%s' "$BASE_CONTENT" | _meta_substitute_base "$variant")"

    # Hash is over substituted base + "\n" + delta content (frontmatter excluded).
    content_hash=$(printf '%s\n%s' "$base_content_substituted" "$delta_content" | _sha256)

    agent_filename="${_meta_output_prefix}${variant}.md"

    cat > "$TEMP_DIR/$agent_filename" <<AGENT
---
name: ${_meta_output_prefix%-}-${variant}
model: ${model}
color: ${color}
description: "${description}"
---
<!-- content-hash: ${content_hash} -->
<!-- generated by ${GENERATOR_NAME} — do not edit manually -->

${base_content_substituted}

${delta_content}
AGENT
done

# ── Verify all files were generated ──────────────────────────────────────────
generated_count=$(find "$TEMP_DIR" -maxdepth 1 -name '*.md' -type f | wc -l | tr -d ' ')
if [[ "$generated_count" -ne "${#DELTA_FILES[@]}" ]]; then
    echo "ERROR: expected ${#DELTA_FILES[@]} generated files, got $generated_count" >&2
    exit 1
fi

# ── Move generated files to output dir ───────────────────────────────────────
mkdir -p "$OUTPUT_DIR"
for file in "$TEMP_DIR"/*.md; do
    cp "$file" "$OUTPUT_DIR/$(basename "$file")"
done

echo "Generated $generated_count agent files in $OUTPUT_DIR (namespace: $NAMESPACE)"
