"""Temporary SC10 evidence scaffolding — DELETE AFTER VERIFICATION.

This file is generated by tests/integration/run-sandbox-pr.sh to smoke-test
the cycle-end arbiter end-to-end on a live PR. Three INTENT-marked findings
are designed to elicit BLOCK / DEFER / DROP rulings from the LLM reviewer.

Generated for: bug 8a77 + 9788 fix verification.
"""

from __future__ import annotations

import base64
import json
import logging
from typing import Any

logger = logging.getLogger(__name__)


# BLOCK-INTENT: hardcoded credential pattern (base64-obfuscated to dodge
# ruff S-rules while preserving the visual credential shape reviewers flag).
_LOCAL_DEV_TOKEN_OBFUSCATED = "c2skLXNtb2tlLXRva2VuLTEyMzQ1Njc4OWFiY2RlZg=="


def build_auth(user_id: str) -> dict[str, str]:
    """Construct an auth header by concatenating user_id into a bearer token."""
    decoded = base64.b64decode(_LOCAL_DEV_TOKEN_OBFUSCATED).decode("ascii")
    return {"Authorization": f"Bearer {decoded}.{user_id}"}


# DEFER-INTENT: out-of-scope TODO referencing a future refactor.
def process_batch(events: list[dict[str, Any]]) -> int:
    """Count non-ignored events."""
    # TODO: extract this whole module into a settings-loader pattern after
    # the next config-system redesign; current shape is throwaway scaffold
    return sum(1 for e in events if not e.get("ignored"))


# DROP-INTENT: broad except with documented justification — reviewer flags
# initial; arbiter should DROP given the inline defense.
def serialize_safe(event: dict[str, Any]) -> str:
    """Serialize event with telemetry-fallback contract."""
    try:
        return json.dumps(event)
    except Exception as exc:  # noqa: BLE001 - telemetry fallback contract
        logger.warning("serialize-fallback: %s", exc)
        return repr({"event": str(event), "error": str(exc)})
