#!/usr/bin/env bash
# run-sandbox-pr.sh — SC10 evidence smoke for bug 8a77 + bug 9788.
#
# Purpose
# -------
# Mechanical synthetic-PR smoke test that proves the cycle-end arbiter is
# reachable on a live GitHub PR after BOTH platform fixes have shipped:
#   - bug 9788 (cycle marker format) — PR #257 merged + PR #258 follow-up
#   - bug 8a77 (provenance-skip) — PR #259 (this PR)
#
# The script creates a fresh synthetic-scenario branch off main, pushes a
# crafted scenario file with three INTENT-marked findings, opens a PR, waits
# for CI to reach a terminal state, and asserts on the llm-review job:
#
#   - The `Run LLM review (provenance-aware)` step MUST NOT emit
#     `CONCLUSION: skipped` (regression guard for bug 8a77 fix)
#   - At least one `DSO-Review-Cycle:` PR comment must be posted (regression
#     guard for bug 9788 fix — ledger reconstruction must round-trip)
#
# The script then closes (does NOT merge) the PR. The scenario file is
# ephemeral and lives only on the closed PR.
#
# Manual / opt-in only — NOT run by the default test suite (would create
# real GitHub PRs). Invoke explicitly:
#
#   bash tests/integration/run-sandbox-pr.sh
#
# Optional env overrides:
#   DSO_SANDBOX_REPO=<owner/repo>   default: read from `gh repo view`
#   DSO_SANDBOX_BASE=<branch>       default: main
#   DSO_SANDBOX_BRANCH_PREFIX=<s>   default: sc10-evidence-smoke
#   DSO_SANDBOX_TIMEOUT_SECONDS     default: 1200 (wait-for-pr.sh ceiling)
#   DSO_SANDBOX_KEEP_PR=1           if set, do NOT close the PR at end
#                                   (useful for manual evidence inspection)

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
SCRIPT_NAME="$(basename "$0")"

# ─── Config resolution ──────────────────────────────────────────────────────
REPO="${DSO_SANDBOX_REPO:-}"
if [[ -z "$REPO" ]]; then
    REPO="$(gh repo view --json nameWithOwner --jq .nameWithOwner 2>/dev/null || echo "")"
fi
if [[ -z "$REPO" ]]; then
    echo "ERROR: cannot resolve sandbox repo (set DSO_SANDBOX_REPO or run with gh auth configured)" >&2
    exit 2
fi

BASE_BRANCH="${DSO_SANDBOX_BASE:-main}"
BRANCH_PREFIX="${DSO_SANDBOX_BRANCH_PREFIX:-sc10-evidence-smoke}"
TIMEOUT_SECONDS="${DSO_SANDBOX_TIMEOUT_SECONDS:-1200}"
KEEP_PR="${DSO_SANDBOX_KEEP_PR:-0}"

TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
BRANCH_NAME="${BRANCH_PREFIX}-${TIMESTAMP}"
SCENARIO_FILE="tests/sc10_evidence_TEMP_DELETE_${TIMESTAMP}.py"

echo "=== ${SCRIPT_NAME} starting ==="
echo "REPO:           $REPO"
echo "BASE_BRANCH:    $BASE_BRANCH"
echo "BRANCH_NAME:    $BRANCH_NAME"
echo "SCENARIO_FILE:  $SCENARIO_FILE"
echo "TIMEOUT:        ${TIMEOUT_SECONDS}s"
echo "KEEP_PR:        ${KEEP_PR}"
echo


# ─── Cleanup trap ───────────────────────────────────────────────────────────
PR_NUMBER=""
WORKTREE_PATH=""
LLM_LOG=""
# shellcheck disable=SC2329  # invoked indirectly via `trap cleanup EXIT` below
cleanup() {
    local rc=$?
    if [[ -n "$WORKTREE_PATH" && -d "$WORKTREE_PATH" ]]; then
        git worktree remove --force "$WORKTREE_PATH" 2>/dev/null || true
    fi
    if [[ -n "$BRANCH_NAME" ]]; then
        git branch -D "$BRANCH_NAME" 2>/dev/null || true
    fi
    if [[ -n "$PR_NUMBER" && "$KEEP_PR" != "1" ]]; then
        echo "Closing PR #$PR_NUMBER (set DSO_SANDBOX_KEEP_PR=1 to keep open for inspection)..."
        gh pr close "$PR_NUMBER" --delete-branch 2>/dev/null || true
    fi
    if [[ -n "$LLM_LOG" && -f "$LLM_LOG" ]]; then
        rm -f "$LLM_LOG"
    fi
    return "$rc"
}
trap cleanup EXIT

# ─── Create worktree off main ───────────────────────────────────────────────
echo "[1/6] Creating worktree off $BASE_BRANCH..."
WORKTREE_PATH="$(mktemp -d "${TMPDIR:-/tmp}/sandbox-pr.XXXXXX")"
git fetch origin "$BASE_BRANCH" --quiet
git worktree add "$WORKTREE_PATH" -b "$BRANCH_NAME" "origin/$BASE_BRANCH" --quiet

# ─── Write scenario file ───────────────────────────────────────────────────
echo "[2/6] Writing scenario file: $SCENARIO_FILE"
cat > "$WORKTREE_PATH/$SCENARIO_FILE" <<'PYEOF'
"""Temporary SC10 evidence scaffolding — DELETE AFTER VERIFICATION.

This file is generated by tests/integration/run-sandbox-pr.sh to smoke-test
the cycle-end arbiter end-to-end on a live PR. Three INTENT-marked findings
are designed to elicit BLOCK / DEFER / DROP rulings from the LLM reviewer.

Generated for: bug 8a77 + 9788 fix verification.
"""

from __future__ import annotations

import base64
import json
import logging
from typing import Any

logger = logging.getLogger(__name__)


# BLOCK-INTENT: hardcoded credential pattern (base64-obfuscated to dodge
# ruff S-rules while preserving the visual credential shape reviewers flag).
_LOCAL_DEV_TOKEN_OBFUSCATED = "c2skLXNtb2tlLXRva2VuLTEyMzQ1Njc4OWFiY2RlZg=="


def build_auth(user_id: str) -> dict[str, str]:
    """Construct an auth header by concatenating user_id into a bearer token."""
    decoded = base64.b64decode(_LOCAL_DEV_TOKEN_OBFUSCATED).decode("ascii")
    return {"Authorization": f"Bearer {decoded}.{user_id}"}


# DEFER-INTENT: out-of-scope TODO referencing a future refactor.
def process_batch(events: list[dict[str, Any]]) -> int:
    """Count non-ignored events."""
    # TODO: extract this whole module into a settings-loader pattern after
    # the next config-system redesign; current shape is throwaway scaffold
    return sum(1 for e in events if not e.get("ignored"))


# DROP-INTENT: broad except with documented justification — reviewer flags
# initial; arbiter should DROP given the inline defense.
def serialize_safe(event: dict[str, Any]) -> str:
    """Serialize event with telemetry-fallback contract."""
    try:
        return json.dumps(event)
    except Exception as exc:  # noqa: BLE001 - telemetry fallback contract
        logger.warning("serialize-fallback: %s", exc)
        return repr({"event": str(event), "error": str(exc)})
PYEOF

# ─── Commit + push ──────────────────────────────────────────────────────────
echo "[3/6] Committing and pushing..."
(
    cd "$WORKTREE_PATH"
    git add "$SCENARIO_FILE"
    git commit --quiet -m "sc10-smoke: synthetic scenario for arbiter E2E ($TIMESTAMP)

Generated by tests/integration/run-sandbox-pr.sh — DELETE AFTER VERIFICATION.

Three INTENT-marked findings exercise BLOCK/DEFER/DROP arbiter rulings:
  - BLOCK-INTENT: hardcoded credential pattern in auth header builder
  - DEFER-INTENT: out-of-scope TODO without ticket reference
  - DROP-INTENT: broad except with documented telemetry-fallback contract

Bug 8a77 + 9788 SC10 evidence smoke test."
    git push -u origin "$BRANCH_NAME" --quiet
)

# ─── Open PR ────────────────────────────────────────────────────────────────
echo "[4/6] Opening PR..."
PR_URL="$(
    gh pr create \
        --repo "$REPO" \
        --base "$BASE_BRANCH" \
        --head "$BRANCH_NAME" \
        --title "[SC10 smoke] Synthetic scenario for arbiter E2E ($TIMESTAMP)" \
        --body "Auto-generated by \`tests/integration/run-sandbox-pr.sh\` to smoke-test the cycle-end arbiter end-to-end after bug 8a77 + 9788 fixes ship.

This PR will be **closed (not merged)** by the smoke script after CI completes.

Acceptance criteria:
- llm-review check must NOT emit \`CONCLUSION: skipped\` (bug 8a77 regression guard)
- At least one \`DSO-Review-Cycle:\` PR comment must appear (bug 9788 regression guard)

If either acceptance criterion fails, the smoke script exits non-zero and the PR is closed with the failure visible in the run log."
)"
PR_NUMBER="$(echo "$PR_URL" | grep -oE '[0-9]+$')"
echo "PR opened: #$PR_NUMBER ($PR_URL)"

# ─── Wait for CI ────────────────────────────────────────────────────────────
echo "[5/6] Waiting for CI (timeout ${TIMEOUT_SECONDS}s)..."
PLUGIN_SCRIPTS="$REPO_ROOT/plugins/dso/scripts"
if [[ -x "$PLUGIN_SCRIPTS/wait-for-pr.sh" ]]; then
    # wait-for-pr.sh reads --timeout=SECONDS as a CLI flag (NOT an env var).
    bash "$PLUGIN_SCRIPTS/wait-for-pr.sh" "$PR_NUMBER" \
        --timeout="$TIMEOUT_SECONDS" --repo="$REPO" || {
            rc=$?
            echo "WARNING: wait-for-pr.sh exited $rc — continuing to assertion phase to capture diagnostic state" >&2
        }
else
    echo "WARNING: wait-for-pr.sh not found; polling manually" >&2
    deadline=$(( $(date +%s) + TIMEOUT_SECONDS ))
    until [[ "$(gh pr view "$PR_NUMBER" --json state --jq .state 2>/dev/null)" != "OPEN" ]] || (( $(date +%s) > deadline )); do
        sleep 30
    done
fi

# ─── Assertions ─────────────────────────────────────────────────────────────
echo "[6/6] Running assertions..."

# Find the most recent CI workflow run for this branch.
RUN_ID="$(gh run list --branch "$BRANCH_NAME" --workflow CI --limit 1 --json databaseId --jq '.[0].databaseId' 2>/dev/null || echo "")"
if [[ -z "$RUN_ID" ]]; then
    echo "FAIL: could not locate CI workflow run for branch $BRANCH_NAME"
    exit 1
fi
echo "  CI run ID: $RUN_ID"

# Locate the llm-review job and capture its log.
LLM_JOB_ID="$(gh run view "$RUN_ID" --json jobs --jq '.jobs[] | select(.name=="llm-review") | .databaseId' 2>/dev/null || echo "")"
if [[ -z "$LLM_JOB_ID" ]]; then
    echo "FAIL: llm-review job not found in workflow run $RUN_ID"
    exit 1
fi
echo "  llm-review job ID: $LLM_JOB_ID"

LLM_LOG="$(mktemp "${TMPDIR:-/tmp}/llm-log.XXXXXX")"
gh run view --job="$LLM_JOB_ID" --log > "$LLM_LOG" 2>&1 || true

# Assertion 1: NOT skipped (bug 8a77 regression guard)
if grep -q "CONCLUSION: skipped" "$LLM_LOG"; then
    echo "FAIL: llm-review emitted 'CONCLUSION: skipped' — bug 8a77 regression"
    echo "  → provenance verifier still treats PR-under-review as its own covering PR"
    echo "  → see https://github.com/$REPO/actions/runs/$RUN_ID"
    exit 1
fi
echo "  PASS: llm-review NOT skipped (bug 8a77 fix working)"

# Assertion 2: At least one DSO-Review-Cycle marker comment (bug 9788 regression guard)
CYCLE_MARKER_COUNT="$(gh api "repos/$REPO/issues/$PR_NUMBER/comments" --paginate \
    --jq '[.[] | select(.body | test("DSO-Review-Cycle:"))] | length' 2>/dev/null || echo "0")"
if (( CYCLE_MARKER_COUNT < 1 )); then
    echo "FAIL: no DSO-Review-Cycle PR comments posted — bug 9788 regression"
    echo "  → cycle marker writer or parser regressed"
    echo "  → see https://github.com/$REPO/actions/runs/$RUN_ID"
    exit 1
fi
echo "  PASS: $CYCLE_MARKER_COUNT DSO-Review-Cycle marker(s) posted (bug 9788 fix working)"

# Optional informational checks (do not fail the smoke).
ARBITER_COUNT="$(gh api "repos/$REPO/issues/$PR_NUMBER/comments" --paginate \
    --jq '[.[] | select(.body | test("DSO-Arbiter-Ruling:"))] | length' 2>/dev/null || echo "0")"
echo "  INFO: $ARBITER_COUNT DSO-Arbiter-Ruling comment(s) posted"

ORPHAN_COUNT="$(.claude/scripts/dso ticket list --tag=orphan:deferred_review 2>/dev/null | grep -c '"ticket_id"' || echo 0)"
echo "  INFO: $ORPHAN_COUNT orphan:deferred_review tickets total (system-wide)"

# LLM_LOG is cleaned up by the trap.

echo
echo "================================="
echo "PASS: SC10 smoke succeeded"
echo "  PR:        $PR_URL"
echo "  CI run:    https://github.com/$REPO/actions/runs/$RUN_ID"
echo "  Markers:   $CYCLE_MARKER_COUNT cycle, $ARBITER_COUNT arbiter ruling"
echo "  (PR will be closed by cleanup trap unless DSO_SANDBOX_KEEP_PR=1)"
echo "================================="
exit 0
