#!/usr/bin/env bash
# lockpick-workflow/scripts/reinstall-hooks.sh — Reinstall git hook shims with resilient fallback
#
# Re-runs `pre-commit install` for all three hook types using the current venv,
# then patches the generated shims to add a `poetry run pre-commit` fallback.
#
# This fixes the "pre-commit not found" error that occurs when the main repo venv
# is rebuilt after hooks were last installed. Worktrees share .git/hooks/ with
# the main repo, so a stale INSTALL_PYTHON path in the shim causes commit failures.
#
# The patched shim falls back in this order:
#   1. Current venv's python (INSTALL_PYTHON — freshly set by pre-commit install)
#   2. System `pre-commit` (command -v pre-commit)
#   3. `poetry run pre-commit` (finds the poetry-managed venv automatically)
#   4. Error: none of the above found
#
# Usage:
#   WORKTREE_PATH=/path/to/worktree bash reinstall-hooks.sh
#
# Environment:
#   WORKTREE_PATH (required) — absolute path to the worktree root
#
# Exit codes:
#   0 — Hooks reinstalled and patched successfully
#   1 — WORKTREE_PATH unset, app/ dir missing, or no pre-commit found

set -euo pipefail

# ── Validate input ───────────────────────────────────────────────────────────

if [ -z "${WORKTREE_PATH:-}" ]; then
    echo "ERROR: WORKTREE_PATH is not set. Export it before running this script." >&2
    exit 1
fi

APP_DIR="$WORKTREE_PATH/app"

if [ ! -d "$APP_DIR" ]; then
    echo "ERROR: App directory not found at $APP_DIR" >&2
    exit 1
fi

# ── Locate pre-commit executable ────────────────────────────────────────────

PRECOMMIT=""

# Prefer the venv's pre-commit if it exists and is executable
VENV_PRECOMMIT="$APP_DIR/.venv/bin/pre-commit"
if [ -x "$VENV_PRECOMMIT" ]; then
    PRECOMMIT="$VENV_PRECOMMIT"
elif command -v poetry > /dev/null 2>&1; then
    # Fall back to poetry run — poetry will resolve the correct venv
    PRECOMMIT="poetry"
elif command -v pre-commit > /dev/null 2>&1; then
    PRECOMMIT="pre-commit"
else
    echo "ERROR: No pre-commit found. Tried: $VENV_PRECOMMIT, poetry run pre-commit, system pre-commit" >&2
    echo "  Fix: cd app && poetry install" >&2
    exit 1
fi

# ── Reinstall hooks ──────────────────────────────────────────────────────────

echo "Reinstalling git hooks in $WORKTREE_PATH ..." >&2

cd "$WORKTREE_PATH"

run_precommit_install() {
    local hook_type="$1"
    if [ "$PRECOMMIT" = "poetry" ]; then
        if [ ! -f "$APP_DIR/pyproject.toml" ]; then
            echo "ERROR: pyproject.toml not found at $APP_DIR — cannot run poetry pre-commit install" >&2
            return 1
        fi
        cd "$APP_DIR" && poetry run pre-commit install --hook-type "$hook_type" 2>&1
        cd "$WORKTREE_PATH"
    else
        "$PRECOMMIT" install --hook-type "$hook_type" 2>&1
    fi
}

for hook_type in pre-commit pre-push prepare-commit-msg; do
    if run_precommit_install "$hook_type"; then
        echo "  Installed hook: $hook_type" >&2
    else
        echo "WARNING: Failed to install $hook_type hook" >&2
    fi
done

# ── Patch hook shims to add poetry run fallback ──────────────────────────────
#
# pre-commit install generates shims that hardcode INSTALL_PYTHON to the venv
# at install time. When the venv is later rebuilt, this path becomes stale and
# the shim fails with "pre-commit not found."
#
# We patch each shim to add `poetry run pre-commit` as a fallback between the
# system `pre-commit` check and the final error.

GIT_DIR=$(git -C "$WORKTREE_PATH" rev-parse --git-dir 2>/dev/null || true)
if [ -z "$GIT_DIR" ]; then
    echo "WARNING: Could not determine git dir; skipping shim patching" >&2
    exit 0
fi

# Resolve to absolute path (git-dir may be relative)
if [[ "$GIT_DIR" != /* ]]; then
    GIT_DIR="$WORKTREE_PATH/$GIT_DIR"
fi

HOOKS_DIR="$GIT_DIR/hooks"

patch_hook_shim() {
    local hook_file="$1"
    [ -f "$hook_file" ] || return 0

    # Check if already patched (avoid double-patching)
    if grep -q "poetry run pre-commit" "$hook_file" 2>/dev/null; then
        return 0
    fi

    # Only patch files that look like pre-commit shims.
    # Accept either the standard generated-by marker OR the characteristic INSTALL_PYTHON
    # variable pattern (for shims that may have been trimmed during testing).
    local is_precommit_shim=0
    if grep -q "File generated by pre-commit" "$hook_file" 2>/dev/null; then
        is_precommit_shim=1
    elif grep -q "INSTALL_PYTHON=" "$hook_file" 2>/dev/null; then
        is_precommit_shim=1
    fi
    if [ "$is_precommit_shim" -eq 0 ]; then
        return 0
    fi

    # Insert `poetry run pre-commit` fallback before the final error line.
    # The error line is: echo '`pre-commit` not found...'
    # We insert a new elif branch before it.
    local tmpfile
    tmpfile=$(mktemp)

    # Use awk to inject the poetry fallback branch before the final error block.
    #
    # The pre-commit shim has this structure:
    #   elif command -v pre-commit > /dev/null; then
    #       exec pre-commit "${ARGS[@]}"
    #   else
    #       echo '`pre-commit` not found...' 1>&2
    #       exit 1
    #   fi
    #
    # We replace the bare `else` line (that precedes the "not found" error) with
    # a new elif-else chain that adds `poetry run pre-commit` as a fallback.
    # To do this safely, we match the `else` followed by the error echo — using a
    # two-line lookahead in awk to ensure we only modify the right `else`.
    awk '
    # Buffer the current line and look ahead
    {
        if (held != "") {
            # Check if held line is "else" and current line is the error echo
            if (held ~ /^else$/ && $0 ~ /echo .*pre-commit.*not found/) {
                print "elif command -v poetry > /dev/null; then"
                print "    exec poetry run pre-commit \"${ARGS[@]}\""
                print "else"
                print $0   # print the original error echo
                held = ""
                next
            } else {
                print held
            }
        }
        held = $0
    }
    END { if (held != "") print held }
    ' "$hook_file" > "$tmpfile"

    # Verify the injection occurred — warn if the sentinel was never matched
    if ! grep -q "poetry run pre-commit" "$tmpfile" 2>/dev/null; then
        echo "WARNING: poetry fallback injection may have failed for $hook_file (sentinel pattern not found)" >&2
    fi

    # Preserve executable bit (chmod --reference is Linux-only; use +x for portability)
    chmod +x "$tmpfile"
    mv "$tmpfile" "$hook_file"
}

patched_count=0
for hook_type in pre-commit pre-push prepare-commit-msg; do
    hook_file="$HOOKS_DIR/$hook_type"
    if [ -f "$hook_file" ]; then
        patch_hook_shim "$hook_file"
        patched_count=$((patched_count + 1))
        echo "  Patched hook shim: $hook_type" >&2
    fi
done

echo "Git hooks reinstalled and patched. ($patched_count shims updated)" >&2
