#!/usr/bin/env bash
# UI Discovery Cache Validation Script
# Generated by ui-discover at <TIMESTAMP>
# DO NOT EDIT — this file is regenerated on every cache refresh.

set -euo pipefail

CACHED_COMMIT="<SHORT_SHA>"

# Embedded UI file include patterns (one per line)
UI_PATTERNS=(
  '*.html' '*.css' '*.scss' '*.js'
)

# Embedded exclusion patterns
EXCLUDE_PATTERNS=(
  '*.test.*' '*.spec.*' '__tests__/*'
  '*.py' '*.rb' '*.go' '*.java' '*.rs' '*.sql'
  '*.md' '*.yaml' '*.toml'
  'node_modules/*' '.venv/*' 'htmlcov/*' '__pycache__/*'
  'dist/*' 'build/*'
)

# Embedded theme files (changes trigger theme-global scope)
THEME_FILES=( <LIST_OF_THEME_FILES> )

# Embedded root layout files (changes trigger shell-global scope)
SHELL_FILES=( <LIST_OF_LAYOUT_FILES> )

# Embedded dependency graph: ENTRY|file1|file2|...
DEPENDS_ON=(
  <ENTRY_DEPENDENCY_LINES>
)
# e.g.: "components/pagination_controls|src/templates/macros/pagination.html"
# e.g.: "routes/upload|src/templates/upload.html|src/templates/base.html"

# --- Step 1: Compare commits ---
CURRENT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null)
if [ -z "$CURRENT_COMMIT" ]; then
  echo '{"status":"error","reason":"git not available"}'
  exit 1
fi

if [ "$CACHED_COMMIT" = "$CURRENT_COMMIT" ]; then
  echo '{"status":"valid"}'
  exit 0
fi

# --- Step 2: Get changed files ---
CHANGED_FILES=$(git diff "$CACHED_COMMIT" "$CURRENT_COMMIT" --name-only 2>/dev/null)
if [ $? -ne 0 ]; then
  echo '{"status":"error","reason":"cached commit not in git history"}'
  exit 1
fi

if [ -z "$CHANGED_FILES" ]; then
  echo '{"status":"valid"}'
  exit 0
fi

# --- Step 3: Filter to UI files only ---
UI_CHANGED=()
while IFS= read -r file; do
  is_excluded=false
  for pat in "${EXCLUDE_PATTERNS[@]}"; do
    case "$file" in
      $pat) is_excluded=true; break ;;
    esac
  done
  if $is_excluded; then continue; fi

  is_ui=false
  for pat in "${UI_PATTERNS[@]}"; do
    case "$file" in
      *$pat) is_ui=true; break ;;
    esac
  done
  # Also match exact theme/config filenames
  basename_file=$(basename "$file")
  for pat in "${UI_PATTERNS[@]}"; do
    case "$basename_file" in
      $pat) is_ui=true; break ;;
    esac
  done

  if $is_ui; then
    UI_CHANGED+=("$file")
  fi
done <<< "$CHANGED_FILES"

if [ ${#UI_CHANGED[@]} -eq 0 ]; then
  echo '{"status":"valid"}'
  exit 0
fi

# --- Step 4: Map changed files to stale entries ---
STALE_ENTRIES=()
SCOPE=""

for entry_line in "${DEPENDS_ON[@]}"; do
  IFS='|' read -ra parts <<< "$entry_line"
  entry="${parts[0]}"
  for changed in "${UI_CHANGED[@]}"; do
    for ((i=1; i<${#parts[@]}; i++)); do
      if [ "${parts[$i]}" = "$changed" ]; then
        STALE_ENTRIES+=("$entry")
        break 2
      fi
    done
  done
done

# --- Step 5: Detect scope ---
for changed in "${UI_CHANGED[@]}"; do
  for tf in "${THEME_FILES[@]}"; do
    if [ "$changed" = "$tf" ]; then
      SCOPE="theme-global"
      break 2
    fi
  done
done

if [ -z "$SCOPE" ]; then
  for changed in "${UI_CHANGED[@]}"; do
    for sf in "${SHELL_FILES[@]}"; do
      if [ "$changed" = "$sf" ]; then
        SCOPE="shell-global"
        break 2
      fi
    done
  done
fi

if [ -z "$SCOPE" ]; then
  has_component=false
  has_route=false
  for entry in "${STALE_ENTRIES[@]}"; do
    case "$entry" in
      components/*) has_component=true ;;
      routes/*) has_route=true ;;
    esac
  done
  if $has_component && $has_route; then
    SCOPE="component-only"
  elif $has_route; then
    SCOPE="route-partial"
  elif $has_component; then
    SCOPE="component-only"
  else
    SCOPE="route-partial"
  fi
fi

# --- Step 6: Output result ---
# Build JSON arrays manually (no jq dependency)
stale_json="["
first=true
for entry in "${STALE_ENTRIES[@]}"; do
  if $first; then first=false; else stale_json+=","; fi
  stale_json+="\"$entry\""
done
stale_json+="]"

changed_json="["
first=true
for file in "${UI_CHANGED[@]}"; do
  if $first; then first=false; else changed_json+=","; fi
  changed_json+="\"$file\""
done
changed_json+="]"

echo "{\"status\":\"stale\",\"scope\":\"$SCOPE\",\"staleEntries\":$stale_json,\"changedFiles\":$changed_json}"
exit 0
